- name: "Introduction"
  shape: |
    XX-
    XXX
    XXX
  structures:
  - OxygenProducer
  - Generator
  constraints:
    resources:
      Oxygen: 2
      Electricity: 0

- name: "Tessellate"
  shape: |
    XXXX-
    XXXXX
    XXXXX
    XXXXX
    XXXXX
  structures:
  - OxygenProducer
  - Generator
  constraints:
    structures:
      OxygenProducer: 2
      Generator: 4

- name: "Green"
  shape: |
    XXXXXXXXXXX
    XXXXXXXXXXX
    -X-X-X-X-X-
  structures:
  - OxygenProducer
  - Generator
  - Plants
  constraints:
    resources:
      Oxygen: 5
      Electricity: 0
