OxygenProducer:
  name: Oxygen Producer
  appearance:
    fill: [0, 100, 255]
    accent: [0, 50, 150]
  shape: |
    XX
    O-
    X-
  produces:
    Oxygen: 2
  consumes:
    Electricity: 1

OxygenProducerV2:
  name: Oxygen Producer V2
  appearance:
    fill: [0, 153, 153]
    accent: [0, 60, 60]
  shape: |
    X--
    XOX
    XXX
  produces:
    Oxygen: 5
  consumes:
    Electricity: 2

Generator:
  name: Generator
  appearance:
    fill: [255, 255, 0]
    accent: [130, 130, 0]
  shape: |
    OX
    XX
  produces:
    Electricity: 2

GeneratorV2:
  name: Generator V2
  appearance:
    fill: [255, 128, 0]
    accent: [130, 60, 0]
  shape: |
    XXX
    XOX
    XXX
  produces:
  Electricity: 5

Plants:
  name: Plants
  appearance:
    fill: [50, 255, 50]
    accent: [25, 130, 25]
  shape: |
    XX
    XO
    -X
  produces:
    Oxygen: 1

Operations:
  name: Operations
  appearance:
    fill: [0, 0, 255]
    accent: [0, 0, 130]
  shape: |
    X--
    X--
    OXX
  consumes:
    Electricity: 1

OperationsV2:
  name: Manned Operations
  appearance:
    fill: [100, 100, 255]
    accent: [50, 50, 130]
  shape: |
    X--
    XO-
    XXX
  consumes:
    Electricity: 1

Medical:
  name: Medical Bay
  appearance:
    fill: [255,0,0]
    accent: [130,0,0]
  shape: |
    -X-
    XOX
    -X-  
  consumes:
    Electricity: 1

Thrusters:
  name: Thrusters
  appearance:
    fill: [120, 0, 120]
    accent: [60, 0, 60]
  shape: |
    XOX
    -X-
  consumes:
    Electricity: 1

Factory:
  name: Factory
  appearance:
    fill: [120, 0, 0]
    accent: [60, 0, 0]
  shape: |
    XXX
    XXX
    XOX
    XXX
    XXX
  consumes:
    Electricity: 2

Quarters:
  name: Quarters
  appearance:
    fill: [255, 0, 255]
    accent: [130, 0, 130]
  shape: |
    XXX
    XOX
    -X-
  consumes:
    Oxygen: 1
