OxygenProducer:
  name: Oxygen Producer
  colour: [0, 100, 255]
  shape: |
    XX
    O-
    X-
  produces:
    oxygen: 2
  consumes:
    electricity: 1
Generator:
  name: Generator
  colour: [255, 255, 0]
  shape: |
    XX
    XX
