bgColour: [60, 60, 120, 100]
titleBar:
  background: [60, 60, 160, 200]
  weight: 0.05
buttonHover: [100,100,200]
text:
  colour: [200, 200, 200]
  size: 40
controls: >
  Use the mouse to position each structure.

  Left click to place the structure.

  Right click to delete an existing structure.

  Press R to rotate a structure before placing.

about: >
  Space LTD was made for Ludum Dare 54 with the theme of 'Limited Space'.


  It was made by the people at fency.fun. Check it out for more fun projects.


  It's written with p5.js, and all of the code is available at
  github.com/eph-eye-en/ld54.
